@startuml
'https://plantuml.com/sequence-diagram

interface DAO {
    + getData(List<String> leaderboard):void;
    + {static} addData(String username, int score, String date) :void
    + {static} readData(List<String> leaderboard):void;
    + {static} deleteData() :void;
}

class ScoreDAO {
    + getData(List<String> leaderboard):void;
    + {static} addData(String username, int score, String date) :void
    + {static} readData(List<String> leaderboard):void;
    + {static} deleteData() :void;
    + {static} sortData(List<String> leaderboard):void;
}
DAO <|.. ScoreDAO
@enduml